### ISSUE TITLE
Running the docker compose VNC-Service gives a warning and then exits.

### ISSUE THREAD

**Issue by BnjBlm** [amrsa1/Android-Emulator-image#11]
`$ docker compose up VNC-Service`

```
WARN[0000] The "START_VNC" variable is not set. Defaulting to a blank string.
[+] Running 1/0
 ✔ Container VNC-Service  Created                                0.0s
Attaching to VNC-Service
VNC-Service exited with code 0
```

**Comment by amrsa1** [comment]
@BenBlumer 

try the following :

```
  VNC-Service:
    image: android-emulator
    build: .
    ports:
      - 5900:5900
    container_name: VNC-Service
    environment: 
      VNC_PASSWORD: 123
    privileged: true
    command:
      - bash
      - -c
      - |
        ./start_vnc.sh
    tty: true
    stdin_open: true
```
